apiVersion: v1
kind: Service
metadata:
  name: info-api
  labels:
    app: info-api
spec:
  type: ClusterIP
  selector:
    app: info-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP