apiVersion: v1
kind: Service
metadata:
  name: serve
  labels:
    app: serve
spec:
  type: ClusterIP
  selector:
    app: serve
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP